### ISSUE TITLE
Unable to access private key

### ISSUE THREAD

**Issue by xcambar** [sjoerdmulder/teamcity-docker#1]
Hi,

I've encountered the following error while trying to use your Dockerfile:

`could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied`

This is apparently related to an AUFS bug (https://github.com/docker/docker/issues/783).
I didn't try any of the workarounds, but hopefully this will help you to come out with a patch :)

**Comment by sjoerdmulder** [comment]
Sorry for late response but i have moved the Postgress out of the teamcity image so this isn't an issue anymore
