### ISSUE TITLE
updated image (TC upgraded) and now cant boot, help please?!

### ISSUE THREAD

**Issue by nicpillinger** [sjoerdmulder/teamcity-docker#13]
After updating my container to use a new image built from here TC is complaining that another instance of TC is running - any ideas on how to solve this? I store my configs outside the container and mount them so reboots arent normally an issue. thanks in advance

https://www.dropbox.com/s/27ly9obbi9kteyn/Screenshot%202016-05-24%2009.12.43.png?dl=0

**Comment by sjoerdmulder** [comment]
It seems that you run 2 TC's at the same time. I had this once and solved it by turning off the other TC and then restarting the 'only' TC running :)

**Comment by nicpillinger** [comment]
TC is started by the docker container though - not sure how 2 got started ok, will try and figure it out. thanks

**Comment by sjoerdmulder** [comment]
Yes, the docker containers starts 1 but most likely the issue is that you have 2 docker containers running.

**Comment by nicpillinger** [comment]
quick update: I've sorted it. There was only 1 container running. I think its to do with the way cloud66 deploys containers - it deploys the new one before the old one is decommissioned so for a time there were 2 containers running (even though when I looked there weren't). TC must have got stuck in that error state, as soon as I restarted the container everything was back to normal. Cheers
