### ISSUE TITLE
Issues downloading postgresql

### ISSUE THREAD

**Issue by ArturKarbone** [sjoerdmulder/teamcity-docker#14]
Hi

 I keep getting the following error:

Downloading postgress JDBC driver...
--2016-07-19 12:17:57--  https://jdbc.postgresql.org/download/postgresql-9.3-1103.jdbc41.jar
Resolving jdbc.postgresql.org (jdbc.postgresql.org)... 174.143.35.228, 2001:4800:1501:1::228
Connecting to jdbc.postgresql.org (jdbc.postgresql.org)|174.143.35.228|:443... connected.
ERROR: The certificate of ‘jdbc.postgresql.org’ is not trusted.
ERROR: The certificate of ‘jdbc.postgresql.org’ hasn't got a known issuer.

running **docker run  sjoerdmulder/teamcity**

Not sure but maybe it is somehow proxy related. Without configuring proxy for docker i was not able even to pull any image. Now i can, but with this particular one  facing the issue descibed above.

**UPDATE:**
When run **wget  https://jdbc.postgresql.org/download/postgresql-9.3-1103.jdbc41.jar**
inside my docker machine it runs just fine.

Thanks

**Comment by sjoerdmulder** [comment]
Not sure what causes that issue, looks like it has some outdated dependencies

**Comment by pjotrok** [comment]
Please check your network connection, could it be that you are behind some proxy?
Try to check SSL certificates by running command `openssl s_client -showcerts -connect jdbc.postgresql.org:443`

**Comment by sjoerdmulder** [comment]
1. Try pulling a new version using `docker pull`
2. If building yourself make sure you use the `--pull` option with `docker build`

Closing this issue now since its not related with Teamcity docker image but outdated enviroment
