### ISSUE TITLE
Seems RemoteIpValve conf is not full enough for TC 2017.1.3

### ISSUE THREAD

**Issue by andreichenchik** [sjoerdmulder/teamcity-docker#31]
Hello,
Seems this line
https://github.com/sjoerdmulder/teamcity-docker/blob/2a13328cb0e124239a218e6625d964df11603d4a/Dockerfile#L12

changed in latest version of TC docs
https://confluence.jetbrains.com/display/TCD10/How+To...#HowTo...-Proxy-Tomcat-RemoteIpValve

to: 
`<Valve
   className="org.apache.catalina.valves.RemoteIpValve"
   remoteIpHeader="x-forwarded-for"
   protocolHeader="x-forwarded-proto"
   portHeader="x-forwarded-port"
   />`

But I'm not sure, maybe I'm getting an error `Details: Host = 'localhost:443' while the browser host value is: 'builder.team.com'` for another reason. 

Thanks for teamcity-docker!

**Comment by oktos-product** [comment]
Created a pull request with fix https://github.com/sjoerdmulder/teamcity-docker/pull/32

**Comment by oktos-product** [comment]
Hm, tested in https://hub.docker.com/r/titanium2product/teamcity-docker/ and it seems that it's not enough to fix the problem. Maybe need to update the hostname somewhere?

**Comment by sjoerdmulder** [comment]
Hi, i'm not actively using Teamcity anymore so i don't have time to test but if there is a fix available i'm willing to merge ;)

**Comment by oktos-product** [comment]
@sjoerdmulder I've double checked, seem I also had an issue in nginx.conf. So the proposed changes seems to be working and consider them to be good for merge.

**Comment by sjoerdmulder** [comment]
Ok, merged it now
