### ISSUE TITLE
Please describe the process of starting an agent from the same image

### ISSUE THREAD

**Issue by aleksandr-vin** [sjoerdmulder/teamcity-docker#6]
For now I've decided to have a quick hack running it in one container with server:

```
docker exec -it teamcity_server /opt/TeamCity/buildAgent/bin/agent.sh run
```

But this scheme breaks the Docker best practices to have one process per container.

Please consider an easy description of running agent in a separate container from the same image with a link.

**Comment by sjoerdmulder** [comment]
Hi,

You can use the `sjoerdmulder/teamcity-agent` for that which also has
instructions in the readme
Op 1 dec. 2015 22:36 schreef "Aleksandr Vinokurov" <notifications@github.com
