### ISSUE TITLE
Teamcity cannot connect to postgres after postgres containers was restarted

### ISSUE THREAD

**Issue by manycoding** [sjoerdmulder/teamcity-docker#7]
So I stopped and started teamcity and postgres containers, and now teamcity shows me the page as it is a new installation.
When trying to connect to postgres, obviously it tells that a teamcity scheme is already found.
I don't quite understand why it happens, as far as I know database settings is stored in the teamcity data directory which is a mounted directory.

**Comment by manycoding** [comment]
I discovered that path to my data folder has changed, so I created a new teamcity container.
But it seems that data wasn't being saved in the data folder for almost 2 weeks, so I ended up with an old project.!
I just wonder where is actually all data now.

**Comment by sjoerdmulder** [comment]
You can always inspect the changes in the old image by using `docker inspect`

**Comment by manycoding** [comment]
I'm afraid that by starting the old container with wrong folder I mounted an empty directory to directory with actual teamcity data. By doing that, I deleted all data.

**Comment by manycoding** [comment]
The most obvious would be that because the mounted directory on my disk became unavailable (its path was changed), and because container data directory was mounted as tmpfs, the data directory was emptied when the container stopped.
