### ISSUE TITLE
No enough space?

### ISSUE THREAD

**Issue by wedkarz** [sjoerdmulder/teamcity-docker#8]
I receive this error when trying to create container/pull image:

Error pulling image (latest) from docker.io/sjoerdmulder/teamcity, Untar re-exec error: exit status 1: output: write /opt/TeamCity/webapps/ROOT/WEB-INF/plugins/idea-tool/agent/idea.zip: no space left on device

**Comment by sjoerdmulder** [comment]
That means you don't have enough space left on the device, are you running in ro mode or are your disks full?
